name: Build TorchAudio Linux Wheels

on:
  workflow_dispatch

jobs:
  run-reusable-build-workflow:
    uses: pytorch/test-infra/.github/workflows/build_wheels_linux_reusable.yml@nirav_reusable_wf_script
