name: Build TorchAudio Linux Wheels

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  binary_linux_wheel:
    uses: pytorch/test-infra/.github/workflows/build_wheels_linux_reusable.yml@nirav_reusable_wf_script
    with:
      repository: "audio"
      docker_image: "pytorch/manylinux-cuda113"
      python_version: "3.7"
      gpu_arch_version: "cu113"