name: Lint

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  python-source-and-configs:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      repository: pytorch/audio
      script: |
        set -euo pipefail

        echo '::group::Setup environment'
        CONDA_PATH=$(which conda)
        eval "$(${CONDA_PATH} shell.bash hook)"
        conda create --name ci --quiet --yes python=3.8 pip
        conda activate ci
        CONDA_RUN="conda run -n ci"
        echo '::endgroup::'
        
        echo '::group::Install lint tools'
        ${CONDA_RUN} PY_PKGS_DIR=${PATH%%:*}
        ${CONDA_RUN} pip install --upgrade pip
        ${CONDA_RUN} pip install --progress-bar=off pre-commit -t "${PY_PKGS_DIR}"
        ${CONDA_RUN} ls "${PY_PKGS_DIR}"
        set +e
        # export PATH=${PATH}:/root/.local/bin
        ${CONDA_RUN} echo $PATH
        ${CONDA_RUN} "${PY_PKGS_DIR}"/pre-commit run --all-files
        
        if [ $? -ne 0 ]; then
          git --no-pager diff
          exit 1
        fi
        echo '::endgroup::'
